nev = input('Hogy hívnak téged?')
print('Szervusz ', nev, ', örülök, hogy találkoztunk.', sep='')
születesi_ev = input ('Mi a születési éved?')
csillagjegy = input ('Mi a csillag jegyed?')
print('Szervusz ', nev, ', örülök, hogy találkoztunk.', sep='')
print ('születési idő: ',születesi_ev)
print ('csillagjegy: ',csillagjegy)